# In Ansible variables can be declared in multiple places.
# Ansible variable can be accessed with {{ }} same like ${} in shell

#- name: Play level variables
#  hosts: localhost
#  connection: local
#  vars:
#    url: play.example.com
#  tasks:
#    - name: Print url
#      ansible.builtin.debug:
#        msg: url - {{ url }}

## Since the variable is declared on play level , then all the tasks can access that variable
#
- name: Task level variable
  hosts: localhost
  connection: local
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}
      vars:
        url: tasks.example.com
#
#- name: Variable Data types
#  hosts: localhost
#  connection: local
#  vars:
#    x: abc
#    y: 100 # we can also use float values like 1.20001
#    z: true
#  tasks:
#    - name: Print url
#      ansible.builtin.debug:
#        msg: x - {{ x }} , y - {{ y }}, z - {{ z }}
#
#- name: Variable Declaration types
#  hosts: localhost
#  connection: local
#  vars:
#    x: abc
#    y:
#      - 100
#      - 200
#    z:
#      url: sample
#      domain: example.com
#  tasks:
#    - name: Print url
#      ansible.builtin.debug:
#        msg: x - {{ x }} , y - {{ y[0] }}, z - {{ z["domain"] }}